---
- name: Deploy Maven Artifact
  hosts: webserver
  become: no
  tasks:
    - name: Copy JAR file to Home Directory
      copy:
        src: ../target/myapp-1.0-SNAPSHOT.jar
        dest: /home/dih/myapp.jar
        mode: "0644"

    - name: Verify file upload
      shell: ls -l /home/dih/myapp.jar
      register: file_check

    - name: Print verification
      debug:
        msg: "The artifact has been successfully deployed to {{ file_check.stdout }}"
